export const BlogColumnsSpec = [
  { data: 'id' },
  { data: 'slug' },
  { data: 'name' },
  { data: 'name_english' },
  { data: 'featured' },
  { data: 'description' },
  { data: 'description_english' },
  { data: 'short_description' },
  { data: 'short_description_english' },
  { data: 'meta_description' },
  { data: 'meta_description_english' },
  { data: 'cover_image_id' },
  { data: 'category_id' },
  { data: 'sub_category_id' },
  { data: 'tags' },
  { data: 'writer' },
  { data: 'co_writer' },
  { data: 'editor' },
  { data: 'video_embed_link' },
  { data: 'status' },
  { data: 'publish_date' },
  // { "data": "persona_writer" },
  // { "data": "short_bio" },
  // { "data": "short_bio_english" },
  // { "data": "persona_editor" },
  // { "data": "list_category" },
  // { "data": "list_subcategory" },
  // { "data": "list_tags" },
  // { "data": "list_co_writer" },
];
